$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
useGitIgnore: true
words:
  - autodocs
  - kazupon
  - lightningcss
  - nuxi
  - nuxt
  - nuxtjs
  - otemachi
  - palt
  - rolldown
  - textareas
  - textlint
  - tokusho
  - ubugeeei
  - vuefes
  - vuejs
  - vuetify
  - webgl
ignorePaths:
  - dist
  - node_modules
  - pnpm-lock.yaml
  - app/assets/fonts/external
  - app/assets/icons
