$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
useGitIgnore: true
words:
  - Abramov
  - allscale
  - allspeed
  - autodocs
  - Chau
  - dateness
  - dominikg
  - fract
  - Guillaume
  - hashimoto
  - Hinomaru
  - Hiroshi
  - inputtext
  - intlify
  - Ishii
  - johnsoncodehk
  - Kawaguchi
  - kazu
  - kazupon
  - Kazuya
  - kgierke
  - kiaking
  - lacunarity
  - lightningcss
  - matcha
  - noindex
  - noopener
  - noreferrer
  - nuxi
  - nuxt
  - nuxtjs
  - nwtgck
  - ogawa
  - otemachi
  - palt
  - pcnextbutton
  - pcprevbutton
  - primevue
  - rolldown
  - sugiura
  - Sumi
  - suminagashi
  - textareas
  - textlint
  - themself
  - tokusho
  - ubugeeei
  - unhead
  - unplugin
  - VEJHSZH
  - vuefes
  - vuejs
  - vuetify
  - vueuse
  - webgl
  - yuji
ignorePaths:
  - dist
  - node_modules
  - pnpm-lock.yaml
  - app/assets/fonts/external
  - app/assets/icons
  - CHANGELOG.md
