$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
useGitIgnore: true
words:
  - allscale
  - allspeed
  - autodocs
  - fract
  - Hinomaru
  - inputtext
  - Kawaguchi
  - kazu
  - kazupon
  - Kazuya
  - kgierke
  - lacunarity
  - lightningcss
  - nuxi
  - nuxt
  - nuxtjs
  - nwtgck
  - otemachi
  - palt
  - primevue
  - rolldown
  - Sumi
  - suminagashi
  - textareas
  - textlint
  - tokusho
  - ubugeeei
  - unplugin
  - vuefes
  - vuejs
  - vuetify
  - webgl
ignorePaths:
  - dist
  - node_modules
  - pnpm-lock.yaml
  - app/assets/fonts/external
  - app/assets/icons
