$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
useGitIgnore: true
words:
  - abramov
  - acconect
  - Akryum
  - allscale
  - allspeed
  - andpad
  - arounds
  - authjs
  - autodocs
  - barai
  - bengo
  - bsky
  - ceroan
  - chau
  - chiyoda
  - choco
  - chooseicon
  - cloudsign
  - codmon
  - Colada
  - cosme
  - cosmonic
  - crayfisher
  - cyberagent
  - dagashi
  - danielroe
  - databank
  - dateness
  - dominikg
  - emscripten
  - escentier
  - ffef
  - finatext
  - finetext
  - fract
  - ftechno
  - gaearon
  - guillaume
  - Haba
  - hacomono
  - Hanako
  - hanzomon
  - hashimoto
  - healthtech
  - hennge
  - hinomaru
  - Hiranuma
  - hiroshi
  - ikkyu
  - ikyu
  - inputtext
  - intlify
  - ishii
  - istyle
  - Jiro
  - johnsoncodehk
  - JUCE
  - Kaede
  - Kaigi
  - karte
  - katanuki
  - Kato
  - kawaguchi
  - kazu
  - kazupon
  - kazuya
  - keihin
  - kgierke
  - kiaking
  - kinto
  - kodomon
  - lacunarity
  - leaysgur
  - lightningcss
  - Livesense
  - livestreaming
  - lycorp
  - marunouchi
  - matcha
  - medpeer
  - mita
  - NAGAI
  - naitokosuke
  - nakano
  - Naoki
  - naokihaba
  - neginasu
  - Nishihara
  - nitropack
  - nofa
  - noindex
  - noopener
  - noreferrer
  - noriyuki
  - nuxi
  - nuxt
  - nuxtjs
  - nwtgck
  - ogawa
  - otemachi
  - palt
  - pcnextbutton
  - pcprevbutton
  - peatix
  - pontaxx
  - posx
  - presigner
  - primevue
  - QUIC
  - Rahul
  - Rakuten
  - Rinchoku
  - RIZAP
  - RNBO
  - rolldown
  - Saburo
  - Sato
  - sayn
  - senbei
  - Seyschab
  - shiminori
  - shimizu
  - Shingo
  - shinkansen
  - sidebase
  - ssssota
  - stockmark
  - studist
  - sugiura
  - sumi
  - suminagashi
  - tanaka
  - teachme
  - tebiki
  - tenshoku
  - tenugui
  - textareas
  - textlint
  - themself
  - Thorsten
  - tiful
  - todde
  - toei
  - tohoku
  - tokaido
  - tokusho
  - tozai
  - tsuno
  - ubugeeei
  - unhead
  - uniquevision
  - unplugin
  - unrs
  - vados
  - valibot
  - Vashishtha
  - vejhszh
  - visasq
  - vuefes
  - vuejs
  - Vuelidate
  - vuetify
  - vueuse
  - wattanx
  - webauthn
  - webgl
  - webshops
  - workerd
  - xlink
  - yamanoku
  - yamanote
  - yappli
  - Yogo
  - yoshiya
  - Yuichi
  - yuichkun
  - yuji
  - Yuto
  - zari
  - zauel
  - zauer
  - zeiri
  - ZOZO
ignorePaths:
  - dist
  - node_modules
  - pnpm-lock.yaml
  - app/assets/fonts/external
  - app/assets/icons
  - server/db/drizzle
  - CHANGELOG.md
