$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
useGitIgnore: true
words:
  - Abramov
  - Acconect
  - allscale
  - allspeed
  - andpad
  - autodocs
  - bengo
  - Chau
  - CLOUDSIGN
  - codmon
  - cosme
  - cyberagent
  - databank
  - dateness
  - dominikg
  - Finatext
  - Finetext
  - authjs
  - autodocs
  - bsky
  - ceroan
  - Chau
  - chooseicon
  - dateness
  - dominikg
  - FFEF
  - fract
  - ftechno
  - Guillaume
  - hashimoto
  - HENNGE
  - Hinomaru
  - Hiroshi
  - ikkyu
  - Ikyu
  - inputtext
  - intlify
  - Ishii
  - istyle
  - johnsoncodehk
  - KARTE
  - Kawaguchi
  - kazu
  - kazupon
  - Kazuya
  - kgierke
  - kiaking
  - KINTO
  - Kodomon
  - lacunarity
  - lightningcss
  - lycorp
  - livestreaming
  - matcha
  - nakano
  - nitropack
  - noindex
  - noopener
  - noreferrer
  - nuxi
  - nuxt
  - nuxtjs
  - nwtgck
  - ogawa
  - otemachi
  - palt
  - pcnextbutton
  - pcprevbutton
  - peatix
  - posx
  - presigner
  - primevue
  - rolldown
  - Stockmark
  - studist
  - sidebase
  - sugiura
  - Sumi
  - suminagashi
  - Teachme
  - tebiki
  - tenshoku
  - textareas
  - textlint
  - themself
  - tiful
  - tokusho
  - ubugeeei
  - unhead
  - uniquevision
  - unplugin
  - VEJHSZH
  - visasq
  - vuefes
  - vuejs
  - vuetify
  - vueuse
  - webauthn
  - webgl
  - xlink
  - yappli
  - workerd
  - Yoshiya
  - yuji
  - zauel
  - zauer
  - Zeiri
ignorePaths:
  - dist
  - node_modules
  - pnpm-lock.yaml
  - app/assets/fonts/external
  - app/assets/icons
  - server/db/drizzle
  - CHANGELOG.md
