$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
useGitIgnore: true
words:
  - abramov
  - acconect
  - allscale
  - allspeed
  - andpad
  - authjs
  - autodocs
  - bengo
  - bsky
  - ceroan
  - chau
  - chiyoda
  - chooseicon
  - cloudsign
  - codmon
  - cosme
  - cyberagent
  - databank
  - dateness
  - dominikg
  - ffef
  - finatext
  - finetext
  - fract
  - ftechno
  - guillaume
  - hanzomon
  - hashimoto
  - hennge
  - hinomaru
  - hiroshi
  - ikkyu
  - ikyu
  - inputtext
  - intlify
  - ishii
  - istyle
  - johnsoncodehk
  - karte
  - kawaguchi
  - kazu
  - kazupon
  - kazuya
  - keihin
  - kgierke
  - kiaking
  - kinto
  - kodomon
  - lacunarity
  - lightningcss
  - livestreaming
  - lycorp
  - matcha
  - marunouchi
  - mita
  - nakano
  - nitropack
  - noindex
  - noopener
  - noreferrer
  - nuxi
  - nuxt
  - nuxtjs
  - nwtgck
  - ogawa
  - otemachi
  - palt
  - pcnextbutton
  - pcprevbutton
  - peatix
  - posx
  - presigner
  - primevue
  - rolldown
  - shinkansen
  - sidebase
  - stockmark
  - studist
  - sugiura
  - sumi
  - suminagashi
  - teachme
  - tebiki
  - tenshoku
  - textareas
  - textlint
  - themself
  - tiful
  - toei
  - tohoku
  - tokaido
  - tokusho
  - tozai
  - ubugeeei
  - unhead
  - uniquevision
  - unplugin
  - vejhszh
  - visasq
  - vuefes
  - vuejs
  - vuetify
  - vueuse
  - webauthn
  - webgl
  - workerd
  - xlink
  - yamanote
  - yappli
  - yoshiya
  - yuji
  - zauel
  - zauer
  - zeiri
ignorePaths:
  - dist
  - node_modules
  - pnpm-lock.yaml
  - app/assets/fonts/external
  - app/assets/icons
  - server/db/drizzle
  - CHANGELOG.md
