$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
useGitIgnore: true
words:
  - abramov
  - acconect
  - Ainoya
  - akinori
  - Akryum
  - allscale
  - allspeed
  - andpad
  - arisa
  - arounds
  - astrotyotogood
  - astuki
  - atsuki
  - authjs
  - autodocs
  - barai
  - bengo
  - bsky
  - Bucky
  - ceroan
  - chau
  - chiyoda
  - choco
  - chooseicon
  - cloudsign
  - codmon
  - Colada
  - corons
  - cosme
  - cosmonic
  - crayfisher
  - cyberagent
  - dagashi
  - danielroe
  - databank
  - dateness
  - dero
  - dominikg
  - emscripten
  - escentier
  - evenodd
  - ffef
  - finatext
  - finetext
  - fract
  - ftechno
  - fujimmm
  - Fujishiro
  - FUJITA
  - gaearon
  - genj
  - guillaume
  - Gura
  - Haba
  - hacomono
  - Hanako
  - hannoeru
  - hanzomon
  - happylifetaka
  - hashimoto
  - Hasuto
  - healthtech
  - hennge
  - hikkobay
  - hinomaru
  - Hiranuma
  - hiro
  - hiroko
  - hiroshi
  - ikkyu
  - Ikuta
  - ikyu
  - inputtext
  - intlify
  - ishii
  - istyle
  - Jiro
  - jiyuujin
  - johnsoncodehk
  - JUCE
  - Junpei
  - Kaede
  - Kaigi
  - KALUPASU
  - karacoro
  - karan
  - karancoro
  - karte
  - katanuki
  - Kato
  - katsuhiro
  - kawaguchi
  - kazu
  - kazupon
  - kazuya
  - keigo
  - keihin
  - kgierke
  - kiaking
  - kinto
  - Kobari
  - kodomon
  - Kogure
  - kokoe
  - Kota
  - kotafujishiro
  - ktym
  - kurawa
  - lacunarity
  - leaysgur
  - lightningcss
  - Livesense
  - livestreaming
  - lycorp
  - magcho
  - marunouchi
  - matcha
  - medpeer
  - misaki
  - mita
  - miyake
  - mizukirimatsu
  - mnch
  - moabear
  - mooncat
  - Moriguin
  - morishita
  - Murata
  - NAGAI
  - naitokosuke
  - nakano
  - nakayama
  - nakayamaakinori
  - nami
  - Naoki
  - naokihaba
  - naramochi
  - neginasu
  - Nishihara
  - nitropack
  - nofa
  - noindex
  - nokki
  - noopener
  - noreferrer
  - noriyuki
  - Nozomu
  - nozomuikuta
  - nuxi
  - nuxt
  - nuxtjs
  - nwtgck
  - ogawa
  - otemachi
  - palt
  - pcnextbutton
  - pcprevbutton
  - peatix
  - pontaxx
  - posx
  - presigner
  - primevue
  - QUIC
  - Rahul
  - Rakuten
  - Rinchoku
  - ritogk
  - RIZAP
  - RNBO
  - rolldown
  - rowspan
  - rstore
  - rymiyamoto
  - ryoaccount
  - ryuhei
  - Saburo
  - sasagar
  - sasagawaki
  - Sasaki
  - Sato
  - sayn
  - senbei
  - Seyschab
  - shiminori
  - shimizu
  - Shingo
  - shinkansen
  - Shota
  - sidebase
  - Spidernight
  - ssssota
  - stockmark
  - studist
  - sugiura
  - sumi
  - suminagashi
  - tanaka
  - teachme
  - tebiki
  - tenshoku
  - tenugui
  - textareas
  - textlint
  - themself
  - thiha
  - Thorsten
  - tiful
  - tigertrack
  - todde
  - toei
  - tohoku
  - tokaido
  - tokusho
  - Tomoda
  - totocalcio
  - toyo
  - tozai
  - Tsai
  - Tsuchiya
  - tsuno
  - ubugeeei
  - unhead
  - uniquevision
  - unplugin
  - unrs
  - vados
  - valibot
  - Vashishtha
  - vejhszh
  - visasq
  - vuefes
  - vuejs
  - Vuelidate
  - vuetify
  - vueuse
  - wattanx
  - webauthn
  - webgl
  - webshops
  - workerd
  - xlink
  - yamageji
  - yamanoku
  - yamanote
  - yappli
  - Yogo
  - yoshiya
  - Yuhei
  - Yuichi
  - yuichkun
  - yuji
  - Yuka
  - yuki
  - Yurika
  - Yusa
  - yuta
  - Yuto
  - zari
  - zauel
  - zauer
  - zeiri
  - ZOZO
ignorePaths:
  - dist
  - node_modules
  - pnpm-lock.yaml
  - app/assets/fonts/external
  - app/assets/icons
  - server/db/drizzle
  - CHANGELOG.md
