name: Check

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/setup-node-pnpm

      - name: Check Spelling
        run: pnpm spell

      - name: Check Linting
        run: pnpm lint

      - name: Check Types
        run: pnpm check

      - name: Check Building
        run: pnpm build

      - name: Check Building Storybook
        run: pnpm story:build
